spring:
  application:
    name: url-shortener
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

app:
  url:
    ttl-days: 30
    base-url: http://localhost:8080